### PR TITLE
WIP - Issue 16

### LINKED ISSUE #16: Some valid hostnames get rejected as having a public suffix
unknown TLDs seem to result in failure!

```js
    "unknown TLD": {
      topic: function() {
        var cj = new CookieJar();
        var url = 'http://www.foonet.dev';
        assert.isTrue(cj.rejectPublicSuffixes);
        cj.setCookie('a=b; Domain=foonet.dev; Path=/',url,this.callback);
      },
      "doesn't error": function(err,cookie) {
        console.log(err);
        assert.ok(!err);
        assert.ok(cookie);
      },
      "domain was parsed without leading dots": function(err,cookie) {
        assert.equal(cookie.domain, 'foonet.dev');
      },
```

### PR DESCRIPTION
**Pull request by stash**
:construction: work in progress

Fixes #16 

Things that should be made to work
- `a=b; domain=example.dev` should work for `www.example.dev` (Note `.dev` isn't a registered top-level domain)
- `a=b; domain=www.example.dev` should work for `http://www.example.dev`
- `a=b; domain=localhost` should work for `http://localhost:3000` (Note `localhost` isn't a registered top-level domain)

### CODE REVIEW

**Comment by apsavin** [comment]
Just realized that I can't use https://github.com/request/request on my dev environment because it uses tough-cookie and tough-cookie can't set cookie with domain `.bla.dev`.
@stash are you still interesting in this repo?
Is there some alive maintainer?

**Comment by apsavin** [comment]
Looks like we can just close this PR

**Comment by inikulin** [comment]
@apsavin Is issue still exists in v1.1.0 which was released recently?

**Comment by apsavin** [comment]
No: [this](https://github.com/SalesforceEng/tough-cookie/blob/master/test/domain_and_path_test.js#L152) test passes.

**Comment by inikulin** [comment]
@apsavin Thanks for taking a look. Closing this PR.

**Pull request closed without merging**
