### PR TITLE
Fix work with public suffixes. Fixes #16

### LINKED ISSUE #16: Some valid hostnames get rejected as having a public suffix
unknown TLDs seem to result in failure!

```js
    "unknown TLD": {
      topic: function() {
        var cj = new CookieJar();
        var url = 'http://www.foonet.dev';
        assert.isTrue(cj.rejectPublicSuffixes);
        cj.setCookie('a=b; Domain=foonet.dev; Path=/',url,this.callback);
      },
      "doesn't error": function(err,cookie) {
        console.log(err);
        assert.ok(!err);
        assert.ok(cookie);
      },
      "domain was parsed without leading dots": function(err,cookie) {
        assert.equal(cookie.domain, 'foonet.dev');
      },
```

### PR DESCRIPTION
**Pull request by apsavin**

### CODE REVIEW

**Comment by apsavin** [comment]
What's done:

1. Tests from http://publicsuffix.org/list/test.txt replaced with tests from http://mxr.mozilla.org/mozilla-central/source/netwerk/test/unit/data/test_psl.txt?raw=1 (more actual version)
2. public-suffix.txt updated
3. `getPublicSuffix` pass `pubSufTest` now
4. `permuteDomain` tests fixed

@stash if you can review it, merge and publish as 0.13.1 it would be great.

**Comment by stash-sfdc** [comment]
@apsavin Thank you for this pull-request. It looks good. I can only accept PRs from folks who have signed a CLA with Salesforce. Could you (or your company) please sign https://github.com/forcedotcom/idecore/blob/master/SFDC_CLA.pdf and send it to me via e-mail?

**Comment by apsavin** [comment]
Well, it's an unusual requirement, but I've signed and sent the CLA to you.

**Comment by stash-sfdc** [comment]
Fixes #16

**Pull request merged**
